---
# This is a manually triggered workflow to build and publish the MkDocs from the
# main branch to GitHub pages at https://aquasecurity.github.io/starboard.
name: Publish documentation

on:
  workflow_dispatch:
    inputs:
      ref:
        description: The branch, tag or SHA to deploy.
        required: true
jobs:
  deploy:
    name: Deploy documentation
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout main
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.ref }}
          fetch-depth: 0
          persist-credentials: true
      - uses: actions/setup-python@d09bd5e6005b175076f227b13d9730d56e9dcfcb
        with:
          python-version: 3.x
      - run: |
          pip install git+https://${GH_TOKEN}@github.com/squidfunk/mkdocs-material-insiders.git
          pip install mike
          pip install mkdocs-macros-plugin
        env:
          # Note: It is not the same as ${{ secrets.GITHUB_TOKEN }} !
          GH_TOKEN: ${{ secrets.MKDOCS_AQUA_BOT }}
      - run: |
          git config user.name "aqua-bot"
          git config user.email "aqua-bot@users.noreply.github.com"
      - run: |
          mike deploy --push --update-aliases ${{ github.event.inputs.ref }} latest
